// Generated by Xata Codegen 0.18.0. Please do not edit.
import {
  BaseClientOptions,
  buildClient,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "talents",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "Jane Doe" },
      { name: "email", type: "email", unique: true },
      { name: "role", type: "int", notNull: true, defaultValue: "0" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Talents = InferredTypes["talents"];
export type TalentsRecord = Talents & XataRecord;

export type DatabaseSchema = {
  talents: TalentsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://okupter-o32l3d.us-east-1.xata.sh/db/trigyte",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
